# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_engine.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'ai_engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61i_engine.proto\x12\tai_engine\"A\n\x0eYoloDetRequest\x12\x0f\n\x07\x63lasses\x18\x01 \x03(\x05\x12\x0e\n\x06images\x18\x02 \x03(\x0c\x12\x0e\n\x06stream\x18\x03 \x01(\x08\"%\n\x0fYoloDetResponse\x12\x12\n\ndetections\x18\x01 \x03(\t\"7\n\x15InsightFaceRecRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x0f\n\x07max_num\x18\x02 \x01(\x05\"\'\n\x16InsightFaceRecResponse\x12\r\n\x05\x66\x61\x63\x65s\x18\x01 \x03(\t2\xb1\x01\n\x0f\x41iEngineService\x12\x45\n\nYoloDetect\x12\x19.ai_engine.YoloDetRequest\x1a\x1a.ai_engine.YoloDetResponse\"\x00\x12W\n\x0eInsightFaceRec\x12 .ai_engine.InsightFaceRecRequest\x1a!.ai_engine.InsightFaceRecResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_YOLODETREQUEST']._serialized_start=30
  _globals['_YOLODETREQUEST']._serialized_end=95
  _globals['_YOLODETRESPONSE']._serialized_start=97
  _globals['_YOLODETRESPONSE']._serialized_end=134
  _globals['_INSIGHTFACERECREQUEST']._serialized_start=136
  _globals['_INSIGHTFACERECREQUEST']._serialized_end=191
  _globals['_INSIGHTFACERECRESPONSE']._serialized_start=193
  _globals['_INSIGHTFACERECRESPONSE']._serialized_end=232
  _globals['_AIENGINESERVICE']._serialized_start=235
  _globals['_AIENGINESERVICE']._serialized_end=412
# @@protoc_insertion_point(module_scope)
